//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSysMover.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSysMover.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will move to default directory.
        /// </summary>
        internal static string FileMoveDefaultDirectory {
            get {
                return ResourceManager.GetString("FileMoveDefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file found .
        /// </summary>
        internal static string NewFileFound {
            get {
                return ResourceManager.GetString("NewFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right rule found .
        /// </summary>
        internal static string RightRuleFound {
            get {
                return ResourceManager.GetString("RightRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right rule wasn&apos;t found .
        /// </summary>
        internal static string RightRuleNotFound {
            get {
                return ResourceManager.GetString("RightRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory couldn&apos;t create - .
        /// </summary>
        internal static string TargetDirectoryCouldNotCreate {
            get {
                return ResourceManager.GetString("TargetDirectoryCouldNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring a file to the destination folder .
        /// </summary>
        internal static string TransferringFile {
            get {
                return ResourceManager.GetString("TransferringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred file couldn&apos;t move - .
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start watch directory - .
        /// </summary>
        internal static string WatchedDirectory {
            get {
                return ResourceManager.GetString("WatchedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watched directory is not exist - .
        /// </summary>
        internal static string WatchedDirectoryNotExist {
            get {
                return ResourceManager.GetString("WatchedDirectoryNotExist", resourceCulture);
            }
        }
    }
}
